stages:
  - test
  - deploy

test:
  stage: test
  image: continuumio/anaconda:latest
  before_script:
    - conda info -a
    - conda env create ClimateImpactLab/risingverse-py27
    - source activate risingverse-py27
    - pip install git+https://github.com/ClimateImpactLab/open-estimate.git
    - pip install git+https://github.com/ClimateImpactLab/impact-common.git
  script:
  - source activate risingverse-py27
  - pytest -v -m "not imperics_shareddir"

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - cat $GCR_KEY | docker login -u _json_key --password-stdin https://$GCR_HOST
    - docker info
    - docker build -t imperics .
    - docker run --rm imperics --help  # "Testing" the image.
    - docker images
    - docker tag imperics $GCR_HOST/$GCS_PROJECTID/imperics:dev
    - docker push $GCR_HOST/$GCS_PROJECTID/imperics:dev
  only:
    - master
