stages:
  - test
  - deploy

test:
  stage: test
  image: continuumio/anaconda:latest
  before_script:
    - conda info -a
    - conda env create ClimateImpactLab/risingverse
    - source activate risingverse
  script:
  - source activate risingverse
  - pytest -v -m "not imperics_shareddir"

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - export DOCKER_DRIVER="overlay2"
    - cat $GCR_KEY | docker login -u _json_key --password-stdin https://$GCR_HOST
    - docker info
    - docker build -t imperics .
    - docker run --rm imperics imperics --help  # "Testing" the image.
    - docker images
    - docker tag imperics $GCR_HOST/$GCS_PROJECTID/imperics:dev
    - docker push $GCR_HOST/$GCS_PROJECTID/imperics:dev
  only:
    - master
