image: continuumio/anaconda:latest

before_script:
  - conda env create ClimateImpactLab/risingverse-py27
  - conda activate risingverse-py27
  - pip install git+https://github.com/ClimateImpactLab/open-estimate.git
  - pip install git+https://github.com/ClimateImpactLab/impact-common.git

test:
  script:
  - conda activate risingverse-py27
  - pytest
