module: impacts/energy/hddcddspline_t_OTHERIND_other_energy.yml
mode: montecarlo
outputdir: $PWD/mc_output
do_only: interpolation
do_farmers: true
only-models: [CCSM4]
only-ssp: SSP3
only-rcp: rcp85
econcovar:
   class: mean
   length: 15
climcovar:
   class: mean
   length: 15
loggdppc-delta: 9.087
