module: impacts/energy/hddcddmodel.yml
mode: writecalcs
outputdir: /shares/gcp/outputs/energy/impacts-rover
do_farmers: true
do_historical: true
singledir: single-run2_EXTRASUM_FD_FGLS_FE
econcovar:
   class: mean
   length: 15
climcovar:
   class: mean
   length: 15
