module: impacts/energy/hddcddspline_OTHERIND_other_energy-brief.yml
mode: median
outputdir: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_income_spline_GMFD_dm
do_farmers: true
do_historical: true
deltamethod: yes
only-ssp: SSP3
econcovar:
   class: mean
   length: 15
climcovar:
   class: mean
   length: 15
loggdppc-delta: 7.713
