module: impacts/energy/hddcddspline.yml
mode: median
outputdir: /shares/gcp/outputs/energy/impacts-blueghost
do_farmers: false
do_historical: true
deltamethod: no
only-ssp: SSP3
only-iam: high
econcovar:
   class: mean
   length: 15
climcovar:
   class: mean
   length: 15
loggdppc-delta: 9.087
