module: impacts/energy/hddcddmodel.yml
mode: median
outputdir: /shares/gcp/outputs/energy/impacts-rover
do_farmers: true
econcovar:
   class: mean
   length: 15
climcovar:
   class: mean
   length: 15
