mode: writecalcs
outputdir: /shares/gcp/outputs/labor/impacts-woodwork
do_historical: true
singledir: comb_risk_27_37_39_interacted_empshare_noFE_YearlyAverageDay
climcovar:
    class: mean
    length: 30
econcovar:
   class: mean
   length: 15
do_farmers: true
timerate: day
climate: [ tasmax, tasmax_rcspline, tas, tas-poly-2, tas-poly-3, tas-poly-4  ]
models:
  - csvvs: social/parameters/labor/post_replication/spline/combined_interacted_spline-empshare-noFE.csvv
    covariates: [ loggdppc, climtasmax, climtas, climtas-poly-2, climtas-poly-3, climtas-poly-4 ]
    knots: [ 27, 37, 39 ]
    description: labor productivity
    specifications:
        minlost_lo:
            csvv-subset: [0, 6]  # Which columns in CSVV? (0-indexing!)
            csvv-reunit:
                - variable: outcome
                  new-unit: minutes worked by individual
            description: low-risk labor productivity
            indepunit: C
            depenunit: minutes worked by individual  
            description: low-risk labor productivity
            functionalform: cubicspline
            prefix: tasmax_rcspline
            variable: tasmax
        minlost_hi:
            csvv-subset: [6, 12]
            csvv-reunit:
                - variable: outcome
                  new-unit: minutes worked by individual
            indepunit: C
            depenunit: minutes worked by individual
            description: high-risk labor productivity
            functionalform: cubicspline
            prefix: tasmax_rcspline
            variable: tasmax
        riskshare_hi:
            csvv-subset: [12, 18]
            csvv-reunit:
                - variable: outcome
                  new-unit: unitless
            indepunit: C
            depenunit: unitless
            description: share of high-risk labor
            functionalform: coefficients
            variables:
                - 1 [scalar]
    calculation:
        - FractionSum:
            - YearlyAverageDay:
                model: minlost_hi
            - Clip:
                - YearlyAverageDay:  # YearlySumDaily triggers RecursionError starting at openest/generate/daily.py", line 308
                    model: riskshare_hi
                - 0.046444122  # Historical clip min value
                - 0.99408281   # Historical clip max value
            - YearlyAverageDay:
                model: minlost_lo
        - Rebase
