outputdir: outputs/labor/impacts-fedconference-oct2019
# Levels are minutes * wage / elasticity; wage = income / (250 days * 6 hours * 60 minutes); elasticity = 0.5
levels-weighting: population * income / 180000
aggregate-weighting: population * income
infix: wage
targetdir: /shares/gcp/outputs/labor/impacts-fedconference-oct2019/single-24oct/rcp85/CCSM4/high/SSP3
