module: labor
mode: single
outputdir: /home/liruixue/projection_repos/impact-calculations/temp
singledir: single
do_only: interpolation
do_farmers: False
csvvfile: social/parameters/labor/csvv_oct2019/labor_test.csvv
specification: polynomial
