module: mortality
mode: writepolys
outputdir: /shares/gcp/outputs/mortality/impacts-darwin
do_only: interpolation
do_farmers: false
csvvfile: social/parameters/mortality/mortality_nonFGLS_22052018/Agespec_interaction_GMFD_POLY-4_TINV_CYA_NW_w1.csvv
specification: polynomials
clipping: both # both, none, or clip
econcovar:
   class: bartlett
   length: 13
climcovar:
   class: bartlett
   length: 30
   