module: mortality
mode: writepolys
outputdir: /shares/gcp/outputs/mortality/impacts-darwin
do_only: mle
do_farmers: false
econcovar:
   class: bartlett
   length: 13
climcovar:
   class: bartlett
   length: 30
   