module: mortality
mode: single
outputdir: /shares/gcp/outputs/mortality/impacts-cupim
do_only: interpolation
do_farmers: false
csvvfile: social/parameters/mortality/polyspline_dd/quadratic/Agespec_interaction_response_polyspline_10C_25C_order2_GMFD.csvv
specification: linear
clipping: both # both, none, or clip
terms:
  hdds:
    variable: tas-10-spline-poly-2
    unit: C^2
    coeffvar: hdd10
    description: HDD under 10C effect
  cdds:
    variable: tas-25-spline-poly-2
    unit: C^2
    coeffvar: cdd25
    description: CDD over 25C effect
econcovar:
   class: bartlett
   length: 13
climcovar:
   class: bartlett
   length: 30
   