module: mortality
mode: montecarlo
outputdir: outputs/mortality/impacts-darwin
do_only: interpolation
do_farmers: true
csvvfile: social/parameters/mortality/mortality_nonFGLS_22052018/Agespec_interaction_GMFD_POLY-4_TINV_CYA_NW_w1.csvv
specification: polynomials
# gcm: MIROC-ESM

